# Generated by Django 5.1.5 on 2025-01-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_stocks',
            name='stockprice',
            field=models.FloatField(),
        ),
    ]
